apiVersion: v1
kind: Service
metadata:
  name: sms-service
  namespace: sms-ns
spec:
  type: NodePort
  selector:
    app: studentmarkservice
  ports:
    - protocol: TCP
      port: 9900
      targetPort: 9900
      nodePort: 30990
